spring.application.name=arogyasutra
spring.datasource.url=jdbc:mysql://localhost:3306/metlifedb
spring.datasource.username=root
spring.datasource.password=ranjith7@M
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#logging.level.org.springframework = DEBUG
#logging.level.org.hibernate = DEBUG
#logging.level.com.zaxxer.hikari = DEBUG